name: "Curate input data"
description: "Create GCS bucket with input data"
inputs:
  input_gcs_bucket:
    description: "GCS bucket name"
    required: true
  region:
    description: "Region"
    required: true
  file_count:
    description: "Number of files to copy"
    required: true

runs:
  using: "composite"
  steps:
    - name: Create output GCS Bucket
      shell: bash
      run: gcloud storage buckets create gs://${{inputs.output_gcs_bucket}} --location=${{inputs.region}}

    - name: Copy files to the bucket
      shell: bash
      run: for i in `seq 1 ${{inputs.file_count}}`; do gsutil cp .github/mock-data/CCRecords_1564602825.csv gs://${{inputs.output_gcs_bucket}}/file_$i.csv; done

