name: "Poll for job"
description: "Poll till job completes"
inputs:
  job_id:
    description: "JobId"
    required: true
  region:
    description: "Region"
    required: true

runs:
  using: "composite"
  steps:
    - name: Poll
      shell: bash
      run: |
        not_finished=true
        while $not_finished; do
          echo "Polling for job status"
          status=$(gcloud dataflow jobs show ${{inputs.job_id}} --region ${{inputs.region}} | grep "state:" | awk '{print $2}') 
          echo "Job status: $status"
          if [[ "$status" == "Done" ]]; then
            echo "PASSED";
            not_finished=false;
          else
            sleep 60s
          fi
        done
        echo "Job with id ${{inputs.job_id}} completed"