# Configuration file for load testing of DLP Dataflow pipeline

gcp:
  project_id: dlp-dataflow-deid-ci-392604
  region: us-central1
  inspect_template: projects/dlp-dataflow-deid-ci-392604/locations/global/inspectTemplates/dlp-demo-inspect-latest-1689137435622
  deid_template: projects/dlp-dataflow-deid-ci-392604/locations/global/deidentifyTemplates/dlp-demo-deid-latest-1689137435622
  service_account: demo-service-account@dlp-dataflow-deid-ci-392604.iam.gserviceaccount.com

tests:
  - name: Batch1
    load: 10GB
  - name: Batch2
    load: 20GB




