name: "Cleanup resources"
description: "Cleanup BQ and Dataflow job"
inputs:
  job_id:
    description: "JobId"
    required: false
  project_id:
    description: "project_id"
    required: true
  dataset:
    description: "dataset"
    required: true

runs:
  using: "composite"
  steps:
    - name: Cleanup
      if: "!cancelled()"
      shell: bash
      run: bq rm -r -f -d ${{inputs.project_id}}:${{inputs.dataset}}