name: Load testing

on:
#  push:
#    branches:
#      - pipeline_performance
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches:
      - pipeline_performance
  workflow_dispatch:

env:
  PROJECT_ID: "dlp-dataflow-deid-ci-392604"
  REGION: "us-central1"

jobs:
  generate-uuid:
    runs-on: ubuntu-latest

    timeout-minutes: 5

    outputs:
      uuid: ${{ steps.gen-uuid.outputs.uuid }}
      job_name: ${{ steps.gen-uuid.outputs.deid_job_name }}

    steps:
      - name: Generate UUID for workflow
        id: gen-uuid
        run: |
          new_uuid=$(uuidgen)
          modified_uuid=$(echo "$new_uuid" | cut -c1-8 )
          echo "uuid=$modified_uuid" >> "$GITHUB_OUTPUT"

  pre-processing:
    needs: generate-uuid
    runs-on:
      - self-hosted
    timeout-minutes: 5
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2

      - name: Read test details
        id: set-matrix
        run: |
          matrix=$(cat .github/workflows/configs/load_tests_details.json | jq '.' )
          echo "$matrix"
          matrix=$(jq -c . < .github/workflows/configs/load_tests_details.json)
          echo "matrix={\"include\":$(echo $matrix)}"
          echo "matrix={\"include\":$(echo $matrix)}" >> $GITHUB_OUTPUT
          



  run-load-tests:
    needs:
      - generate-uuid
      - pre-processing

    strategy:
      max-parallel: 1
      matrix: ${{ fromJSON(needs.pre-processing.outputs.matrix) }}

    uses: ./.github/workflows/submit-dataflow-job.yml
    with:
      project_id: "dlp-dataflow-deid-ci-392604"
      input_gcs_bucket: "input_dlp_load_test"
      dataset: "load_test_dataset"
      inspect_template: "projects/dlp-dataflow-deid-ci-392604/locations/global/inspectTemplates/dlp-demo-inspect-latest-1689137435622"
      deid_template: "projects/dlp-dataflow-deid-ci-392604/locations/global/deidentifyTemplates/dlp-demo-deid-latest-1689137435622"
      uuid: ${{ needs.generate-uuid.outputs.uuid }}
      test_load: ${{ matrix.name }}

#  publish-test-results:
#    needs:
#      - generate-uuid
#      - pre-processing
#      - run-load-tests
#    runs-on:
#      - self-hosted
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Execute publishMetrics Script
#        run: |
#          python3 .github/workflows/scripts/publishTestReport.py ${{env.PROJECT_ID}} ${{ needs.generate-uuid.outputs.uuid }}
#
#
#
#
#
#
#
#
#
