name: Load testing

on:
#  push:
#    branches:
#      - pipeline_performance
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches:
      - pipeline_performance
  workflow_dispatch:

jobs:
  generate-uuid:
    runs-on: ubuntu-latest

    timeout-minutes: 5

    outputs:
      uuid: ${{ steps.gen-uuid.outputs.uuid }}
      job_name: ${{ steps.gen-uuid.outputs.deid_job_name }}

    steps:
      - name: Generate UUID for workflow
        id: gen-uuid
        run: |
          new_uuid=$(uuidgen)
          modified_uuid=$(echo "$new_uuid" | tr '-' '_')
          modified_uuid=$(echo "$new_uuid" | cut -c1-8 )
          echo "uuid=$modified_uuid" >> "$GITHUB_OUTPUT"
          echo "deid_job_name=load-test-$modified_uuid" >> "$GITHUB_OUTPUT"

  create-input-resources:
    needs: generate-uuid
    runs-on:
      - self-hosted
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2

      - name: execute script
        run: python3 .github/workflows/scripts/fetchJobMetrics.py dlp-dataflow-deid-ci-392604 2024-01-22_23_02_49-12931597370515843515

  #      - name: Create Output GCS Bucket
#        uses: ./.github/workflows/curate-data
#        with:
#          input_gcs_bucket: "input_dlp_load_test"
#          region: "us-central1"
#          file_count: "10"
#      - name: Create BQ Dataset
#        run: bq --location=US mk -d --description "GitHub load test dataset" load_test_dataset

  run-load-tests:
    needs:
      - generate-uuid
      - create-input-resources

    uses: ./.github/workflows/submit-dataflow-job.yml
    with:
      project_id: "dlp-dataflow-deid-ci-392604"
      input_gcs_bucket: "input_dlp_load_test"
      dataset: "load_test_dataset"
      inspect_template: "projects/dlp-dataflow-deid-ci-392604/locations/global/inspectTemplates/dlp-demo-inspect-latest-1689137435622"
      deid_template: "projects/dlp-dataflow-deid-ci-392604/locations/global/deidentifyTemplates/dlp-demo-deid-latest-1689137435622"
      uuid: ${{ needs.generate-uuid.outputs.uuid }}

  poll:
    needs:
      - create-input-resources
      - run-load-tests
    runs-on:
      - self-hosted
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - name: Poll till job finishes
        uses: ./.github/workflows/poll-job
        with:
          job_id: ${{ needs.run-load-tests.outputs.job_id }}
          region: "us-central1"

#      - name: Fetch metrics
#        uses: ./.github/workflows/fetch-metrics
#        with:
#          job_id: ""
#          region: "us-central1"






