name: Load testing

on:
#  push:
#    branches:
#      - pipeline_performance
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches:
      - pipeline_performance
  workflow_dispatch:

jobs:
  create-output-bucket:
    runs-on:
      - self-hosted
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Create Output GCS Bucket
        uses: ./.github/workflows/load-tests
        with:
          output_gcs_bucket: "test_composite"
          region: "us-central1"


