name: Load testing

on:
#  push:
#    branches:
#      - pipeline_performance
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches:
      - pipeline_performance
  workflow_dispatch:

jobs:
  create-input-resources:
    runs-on:
      - self-hosted
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Create Output GCS Bucket
        uses: ./.github/workflows/curate-data
        with:
          output_gcs_bucket: "input_bucket"
          region: "us-central1"
          file_count: "10"
      - name: Create BQ Dataset
        run: bq --location=US mk -d --description "GitHub load test dataset" load_test_dataset

  run-load-tests:
    needs: create-input-resources

    runs-on:
      - self-hosted

    uses: ./.github/workflows/submit-dataflow-job.yml
    with:
      project_id: "dlp-dataflow-deid-ci-392604"
      input_gcs_bucket: "input_bucket"
      dataset: "load_test_dataset"
      inspect_template: "projects/dlp-dataflow-deid-ci-392604/locations/global/inspectTemplates/dlp-demo-inspect-latest-1689137435622"
      deid_template: "projects/dlp-dataflow-deid-ci-392604/locations/global/deidentifyTemplates/dlp-demo-deid-latest-1689137435622"






